# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 2</font>

# Estruturas de Dados em Pandas



pandas.Series()          - 1 Dimensão  - 1D

pandas.DataFrame()  - 2 Dimensões - 2D

pandas.Panel()           - 3 Dimensões - 3D

numpy.ndarray()     - x Dimensões 


# Panel

In [35]:
import pandas as pd
import numpy as np
import warnings
#warnings.filterwarnings("ignore")

In [36]:
data = np.random.randint(1, 10, (5, 3, 2));data

array([[[5, 4],
        [1, 2],
        [6, 2]],

       [[5, 7],
        [6, 5],
        [1, 1]],

       [[9, 7],
        [2, 6],
        [3, 5]],

       [[6, 8],
        [1, 9],
        [7, 3]],

       [[5, 9],
        [4, 6],
        [7, 6]]])

In [37]:
painel = pd.Panel(
    data, 
    items = ['item {}'.format(i) for i in range(1, 6)], 
    major_axis = [2015, 2016, 2017], 
    minor_axis = ['US', 'UK'])

<ipython-input-37-f640f1d7403e>:1: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  painel = pd.Panel(


TypeError: Panel() takes no arguments

In [38]:
print(painel)

NameError: name 'painel' is not defined

In [39]:
data = data.reshape(5, 6).T;data

array([[5, 5, 9, 6, 5],
       [4, 7, 7, 8, 9],
       [1, 6, 2, 1, 4],
       [2, 5, 6, 9, 6],
       [6, 1, 3, 7, 7],
       [2, 1, 5, 3, 6]])

In [40]:
df = pd.DataFrame(
    data = data,
    index = pd.MultiIndex.from_product([[2015, 2016, 2017], ['US', 'UK']]),
    columns = ['item {}'.format(i) for i in range(1, 6)])

In [41]:
df

item 1  item 2  item 3  item 4  item 5
2015 US       5       5       9       6       5
     UK       4       7       7       8       9
2016 US       1       6       2       1       4
     UK       2       5       6       9       6
2017 US       6       1       3       7       7
     UK       2       1       5       3       6

## Criando objetos multidimensionais com Panel

In [42]:
USData = pd.DataFrame(np.array([[249.62 , 8900],
                              [282.16,12680],
                              [309.35,14940]]),
                      columns = ['População(M)','PIB($B)'],
                      index = [1995,2005,2015])

In [43]:
USData

População(M)  PIB($B)
1995        249.62   8900.0
2005        282.16  12680.0
2015        309.35  14940.0

In [44]:
ChinaData = pd.DataFrame(np.array([[1133.68, 390.28],
                                 [1266.83,1198.48],
                                 [1339.72, 9923.47]]),
                       columns=['População(M)','PIB($B)'],
                       index=[1995,2005,2015])

In [45]:
ChinaData

População(M)  PIB($B)
1995       1133.68   390.28
2005       1266.83  1198.48
2015       1339.72  9923.47

In [46]:
US_ChinaData = {'US' : USData,
                'China': ChinaData}

In [47]:
US_ChinaData

{'US':       População(M)  PIB($B)
 1995        249.62   8900.0
 2005        282.16  12680.0
 2015        309.35  14940.0,
 'China':       População(M)  PIB($B)
 1995       1133.68   390.28
 2005       1266.83  1198.48
 2015       1339.72  9923.47}

In [48]:
pd.Panel(US_ChinaData)

<ipython-input-48-249e10396bbe>:1: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  pd.Panel(US_ChinaData)


TypeError: Panel() takes no arguments

In [49]:
pd.concat([US_ChinaData[key].stack() for key in US_ChinaData], 1)

0        1
1995 População(M)    249.62  1133.68
     PIB($B)        8900.00   390.28
2005 População(M)    282.16  1266.83
     PIB($B)       12680.00  1198.48
2015 População(M)    309.35  1339.72
     PIB($B)       14940.00  9923.47

In [50]:
frames = [USData, ChinaData]

https://pandas-docs.github.io/pandas-docs-travis/user_guide/merging.html

In [51]:
pd.concat(frames)

População(M)   PIB($B)
1995        249.62   8900.00
2005        282.16  12680.00
2015        309.35  14940.00
1995       1133.68    390.28
2005       1266.83   1198.48
2015       1339.72   9923.47

In [52]:
np.concatenate(frames)

array([[  249.62,  8900.  ],
       [  282.16, 12680.  ],
       [  309.35, 14940.  ],
       [ 1133.68,   390.28],
       [ 1266.83,  1198.48],
       [ 1339.72,  9923.47]])

In [62]:
type(pd.Panel(US_ChinaData))

<ipython-input-62-5085df422450>:1: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  type(pd.Panel(US_ChinaData))


TypeError: Panel() takes no arguments

## Convertendo DataFrame para Panel

In [66]:
#change labels para codes
mIdx = pd.MultiIndex(levels = [['US', 'China'], [1995,2005, 2015]],
                     codes = [[1,1,1,0,0,0], [0,1,2,0,1,2]])

In [67]:
mIdx

MultiIndex([('China', 1995),
            ('China', 2005),
            ('China', 2015),
            (   'US', 1995),
            (   'US', 2005),
            (   'US', 2015)],
           )

In [68]:
ChinaUSDF = pd.DataFrame({'População(M)' : [1133.68, 1266.83, 1339.72, 249.62, 282.16,309.35], 
                          'PIB($B)': [390.28, 1198.48, 6988.47, 8900,12680,14940]}, 
                         index = mIdx)

In [69]:
ChinaUSDF

População(M)   PIB($B)
China 1995       1133.68    390.28
      2005       1266.83   1198.48
      2015       1339.72   6988.47
US    1995        249.62   8900.00
      2005        282.16  12680.00
      2015        309.35  14940.00

In [70]:
# ChinaUSDF.to_panel()
!pip install xarray

In [71]:
ChinaUSDF.to_xarray()

<xarray.Dataset>
Dimensions:       (level_0: 2, level_1: 3)
Coordinates:
  * level_0       (level_0) object 'US' 'China'
  * level_1       (level_1) int64 1995 2005 2015
Data variables:
    População(M)  (level_0, level_1) float64 1.134e+03 1.267e+03 ... 282.2 309.4
    PIB($B)       (level_0, level_1) float64 390.3 1.198e+03 ... 1.494e+04

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>