In [1]:
import numpy as np

In [2]:
array1 = np.array([10,240,30,40]);array1

array([ 10, 240,  30,  40])

In [3]:
array2 = np.array([[100,83,15],[20,40,83]]);array2

array([[100,  83,  15],
       [ 20,  40,  83]])

In [4]:
array1.shape

(4,)

In [5]:
array2.shape

(2, 3)

In [6]:
array1.ndim

1

In [7]:
array2.ndim

2

In [8]:
array1.max()

240

In [15]:
np.arange(17)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [25]:
array5 = np.arange(0,15,3);array5

array([ 0,  3,  6,  9, 12])

In [26]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [27]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.diag((1,2,2,3,4))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [39]:
#para gerar os mesmos valores randômicos, use o seed
#np.random.seed(100)
np.random.rand(5)

array([0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606])

In [40]:
#distribuição normal - Gaussiana
np.random.randn(7)

array([ 1.56717879,  0.49702472,  1.15587233,  1.83861168,  1.53572662,
        0.25499773, -0.84415725])

In [49]:
#return a new array of given shape and type, without initializing entries.
array12 = np.empty((3,2));array12

array([[4.66051014e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [50]:
array14 = np.array([[1,2],[3,4]]);array14

array([[1, 2],
       [3, 4]])

In [51]:
np.tile(array14,4)

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [57]:
np.tile(array14,(3,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [59]:
array15 = np.array([3,4,-5,9], dtype='float');array15

array([ 3.,  4., -5.,  9.])

In [61]:
array15.dtype

dtype('float64')

In [62]:
array14.dtype

dtype('int64')

In [63]:
array16 = np.array(['Análise','de','dados','com','numpy']);array16

array(['Análise', 'de', 'dados', 'com', 'numpy'], dtype='<U7')

In [64]:
array16.dtype

dtype('<U7')

In [65]:
array17 = np.array([True, True, False, True]); array17

array([ True,  True, False,  True])

In [66]:
array17.dtype

dtype('bool')

In [67]:
array18 = np.array([4,5,3.8,5.9]);array18

array([4. , 5. , 3.8, 5.9])

In [68]:
array18.dtype

dtype('float64')

In [69]:
array18.astype(int)

array([4, 5, 3, 5])

In [71]:
array18.astype('int')

array([4, 5, 3, 5])

In [73]:
array18 * 10

array([40., 50., 38., 59.])

In [74]:
array18 ** 2

array([16.  , 25.  , 14.44, 34.81])

In [75]:
array18 + 2

array([6. , 7. , 5.8, 7.9])

In [84]:
array22 = np.arange(0,60,6)+2;array22

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56])

In [85]:
array23 = np.arange(1,11); array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
array22 - array23

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [87]:
array22 + array23

array([ 3, 10, 17, 24, 31, 38, 45, 52, 59, 66])

In [88]:
array22 / array23

array([2.        , 4.        , 4.66666667, 5.        , 5.2       ,
       5.33333333, 5.42857143, 5.5       , 5.55555556, 5.6       ])

In [89]:
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [91]:
arr1 = np.array([True,False,True,False])

In [90]:
arr2 = np.array([False,False,True,False])

In [93]:
np.logical_and(arr1,arr2)

array([False, False,  True, False])

In [94]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

7.91 µs ± 65.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [98]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

519 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
