### Transposição e reshaping de arrays

In [1]:
import numpy as np

In [5]:
array1 = np.array([[66, 24, 20],[42, 88, 11]]); array1

array([[66, 24, 20],
       [42, 88, 11]])

In [6]:
#pivot/transposição
array1.T

array([[66, 42],
       [24, 88],
       [20, 11]])

In [8]:
#pivot/transposição
np.transpose(array1)

array([[66, 42],
       [24, 88],
       [20, 11]])

### Broadcasting

In [19]:
array2 = np.array([[34, 35, 36]]); array2

array([[34, 35, 36]])

In [20]:
array2.shape

(1, 3)

In [21]:
array2.T

array([[34],
       [35],
       [36]])

In [23]:
array2.T.shape

(3, 1)

In [24]:
array2.T + array2

array([[68, 69, 70],
       [69, 70, 71],
       [70, 71, 72]])

### Transformando matrizes em vetores

In [29]:
array3 = np.array([np.arange(1,7), np.arange(10,16)]); array3

array([[ 1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15]])

In [30]:
array3.ravel()

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12, 13, 14, 15])

In [31]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14,  6, 15])

### Operadores Lógicos

In [37]:
np.random.seed(100)
array4 = np.random.randint(1, 10, size = (4,4)); array4

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [41]:
#qualquer elemento
np.any((array4 % 7) == 0)

False

In [42]:
#todos os elemtnos
np.all(array4  < 11)

True

### Reshaping

In [50]:
array5 = np.arange(1,21); array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
array5.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

### Ordenando o array

In [54]:
array7 = np.array([[3,2],[20,-2]]);array7

array([[ 3,  2],
       [20, -2]])

In [59]:
#ordenando por linhas
# não precisa de atribuição, ele mudo apenas chamando o método
array7.sort(axis=1);array7

array([[ 2,  3],
       [-2, 20]])

In [60]:
#ordenando por coluna
# não precisa de atribuição, ele mudo apenas chamando o método
array7.sort(axis=0);array7

array([[-2,  3],
       [ 2, 20]])